# fly.toml app configuration file generated for weasyprint-sandbox on 2025-11-14T19:19:46-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'weasyprint-sandbox'
primary_region = 'iad'

[build]

[env]
  SECRET_KEY = 'change-this-in-production'

[[mounts]]
  source = 'workspaces_data'
  destination = '/app/workspaces'

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
